app.js, controllers/users.controller.js, package.json, routes/users.route.js, services/users.service.js
- 랜덤으로 인증 번호 생성 후 캐시에 저장
- AWS SNS를 이용하여 인증 번호를 문자로 전송
- 사용자가 입력한 인증 번호와 캐시에 저장된 인증 번호를 대조하여 확인
<br/>
리뷰어가 특별히 봐주었으면 하는 부분이나 주의사항, 알림사항 등이 있다면 작성해주세요.
<br/> ex) 더미 데이터를 넣어서 기능 구현한 상태입니다!
<br/>
=> feat: 문자 인증 API 추가

app.js, controllers/sectors.controller.js, controllers/users.controller.js, db/index.js, models/sectors.model.js, models/users.model.js, package.json, routes/sectors.route.js, routes/users.route.js, services/sectors.service.js, services/users.service.js, utils/encryption.js, validators/users.validator.js
- 업종 조회 API 구현
- 회원가입 API 구현
- 비밀번호 암호화 함수 구현
<br/>
=> feat: 회원가입 API 추가

package.json, src/controllers/users.controller.ts, src/dto/users.dto.ts, src/routes/users.route.ts, src/services/users.service.ts, src/validators/users.validator.ts
- 문자 인증 API 타입스크립트로 수정
<br/>
- controller에서 에러를 처리하면 안되는지
<br/>
=> refactor: 타입스크립트로 수정

src/validators/users.validator.ts
- 회원가입 비밀번호 정규표현식 검사 추가
- 로그인 사업자번호, 비밀번호 유효성 검사 수정
<br/>
=> refactor: 회원가입 비밀번호 유효성 검사 수정

.prettierrc, eslintrc.js, package.json, src/app.ts, src/auth.ts, src/config/config.ts, src/controllers/sectors.controller.ts, src/controllers/users.controller.ts, src/dto/users.dto.ts, src/errorHandler/errorMiddleware.ts, src/models/index.ts, src/models/sectors.model.ts, src/models/tokens.model.ts, src/models/users.model.ts, src/models/wholesalers.model.ts, src/routes/sectors.route.ts, src/routes/users.route.ts, src/services/sectors.service.ts, src/services/users.service.ts, src/utils/aws.ts, src/utils/encryption.ts, src/utils/httpExeption.ts, src/utils/wrapAsyncController.ts, src/validators/users.validator.ts, src/validators/validate.ts
- eslint와 prettier 적용
<br/>
vscode extention에서 아래의 두 플러그인을 설치합니다.
vscode setting에서 아래의 설정을 변경합니다.
1. format on save 활성화
2. javascript formatter 비활성화
3. default formatter에서 prettier - code formatter 선택
=> style: eslint와 prettier 적용

src/models/tokens.model.ts
- token 모델의 token 문자열 길이 수정
<br/>
- jwt 페이로드가 길어져서 토큰을 DB에 넣을 때 잘리는 문제가 발생하여 tokens 테이블의 token 길이를 늘렸습니다.
=> fix: 토큰 길이 수정

src/app.ts, src/services/users.service.ts
- cors origin에 프론트 배포 주소 추가
- allowedHeaders 수정
- user service 사용자 조회 함수 에러 콘솔 로그 제거
<br/>
=> refactor: cors 옵션 수정

src/validators/users.validator.ts
- 로그인 사업자 번호 유효성 검사 수정
- 비밀번호 변경 유효성 검사 수정
<br/>
=> fix: 로그인, 비밀번호 변경 유효성 검사 수정

src/controllers/users.controller.ts, src/routes/users.route.ts, src/validators/users.validator.ts
- 비밀번호 변경 시, password와 rePassword 비교 로직 삭제
<br/>
<br/>
=> refactor: 비밀번호 확인 로직 제거

src/controllers/users.controller.ts, src/services/users.service.ts
=> refactor: 캐시 만료시간 전송

src/app.ts, src/auth.ts, src/controllers/liquors.controller.ts, src/dto/liquors.dto.ts, src/models/likes.model.ts, src/models/liquorCategories.model.ts, src/models/liquors.model.ts, src/routes/liquors.route.ts, src/services/liquors.service.ts, src/validators/liquors.validator.ts
- 주류 카테고리 조회 API 추가
- 공동 구매 요청 (좋아요 추가/삭제) API 추가
- 전통주 목록 조회 API 추가
- 도수 필터링 기능
- 전통주 이름 검색 기능
- 카테고리 필터링 기능
- 전통주 상세 조회 API 추가
<br/>
- 리뷰 관련 내용과 공동 구매 관련 내용은 중간 발표 이후에 구현 예정이기 때문에 
전통주 목록 조회 API에는 별점 기준 정렬 기능이 없는 상태이고,
전통주 상세 조회 API에는 리뷰 개수와 평균 별점, 현재 진행 중인 공동 구매 내역이 없는 상태입니다.
<br/>
=> feat: 전통주 조회 관련 API 추가

src/controllers/users.controller.ts, src/models/index.ts, src/models/users.model.ts, src/models/wholesalers.model.ts, src/routes/users.route.ts, src/services/users.service.ts
- 소상공인, 도매업자 프로필 조회 API 추가
<br/>
공동 구매 관련 내용은 중간 발표 이후에 진행하기 때문에
프로필 조회 API에서 공동구매 현황은 구현하지 않았습니다.
<br/>
=> feat: 프로필 조회 API 추가

src/controllers/users.controller.ts, src/dto/users.dto.ts, src/models/users.model.ts, src/services/users.service.ts, src/validators/users.validator.ts
- 회원가입 API 마케팅 활용 동의 여부 추가
- DB users 테이블 marketing 컬럼 추가
- 로그인 API 도매업자 여부 응답 추가
- access token, refresh token 쿠키 옵션 제거
<br/>
- 쿠키 옵션은 추후 구현될 자동로그인을 위해 제거했습니다.
=> refactor: 회원가입 API 마케팅 활용 동의 여부 추가, 로그인 API 도매업자 여부 응답 수정

package-lock.json, package.json, src/controllers/users.controller.ts, src/dto/users.dto.ts, src/models/users.model.ts, src/services/users.service.ts, src/validators/users.validator.ts
- users 모델 마케팅 활용 동의 여부 컬럼명 수정, default 값 지정
- 회원가입 API 마케팅 활용 동의 여부 변수명 수정
- 로그인 API 도매업자 여부 변수명 수정
<br/>
- multer 모듈이 없다는 에러가 발생하여 설치했습니다.
=> refactor: 마케팅 활용 동의 여부 default 값 지정

.github/workflows/ci.yml, package.json
- ci.yml node 버전 변경
- package.json 파일 node, npm 버전 지정
<br/>
=> chroe: node 버전 지정

src/controllers/users.controller.ts
- 쿠키 설정 변경
- sameSite: false → 'none'
- httpOnly: true → false
<br/>
<br/>
=> fix: 쿠키 설정 수정

src/config/config.ts, src/controllers/users.controller.ts, src/models/withdrawals.model.ts, src/routes/users.route.ts, src/services/liquors.service.ts, src/services/users.service.ts, src/validators/users.validator.ts
- 회원 탈퇴 API 추가
- 로그인, 액세스 토큰 재발급 API 토큰 응답 위치를 cookie에서 body로 변경
- 프로필 조회, 전통주 목록 조회, 전통주 상세 조회 API 응답 중 스네이크 케이스를 카멜 케이스로 변경
- production 환경에서도 SQL문 로그가 남도록 config 파일 수정
<br/>
<br/>
=> feat: 회원 탈퇴 API 추가

.github/workflows/deploy.yml
=> fix: deploy,yml 수정

src/app.ts
- 프론트 배포 주소 cors 설정 변경 (https://licruit.site)
<br/>
=> chore: 프론트 배포 주소 cors 설정

package-lock.json, package.json, src/app.ts, src/errorHandler/errorMiddleware.ts, src/utils/sentry.ts, src/utils/slackWebHook.ts
- sentry 기본 설정
- slack 연동
<br/>
- sentry
- slack
<br/>
=> chore: sentry 설정

src/app.ts
- GET default route 추가
<br/>
- sentry와 연동한 slack에서 GET / 라우터가 없다는 오류가 지속적으로 발생하여 GET / 라우터를 추가했습니다.
=> fix: default route 추가

src/app.ts
- 라우터 not found로 인해 발생하는 에러는 slack 메시지 로그에서 제외
- GET default router 삭제
<br/>
=> fix: 라우터 not found 로그 제외

src/services/users.service.ts
- 비밀번호 변경시 salt도 업데이트
<br/>
변경할 새 비밀번호를 암호화할 때 새로운 salt가 발급되므로 password와 salt를 모두 업데이트 합니다.
<br/>
=> fix: 비밀번호 변경 salt 업데이트

src/controllers/liquors.controller.ts, src/dto/liquors.dto.ts, src/services/liquors.service.ts
- 전통주 목록 조회 query string 카멜 케이스로 변경
- min_alcohol → minAlcohol
- max_alcohol →maxAlcohol
<br/>
=> refactor: 전통주 목록 조회 쿼리 카멜 케이스로 변경

src/services/users.service.ts
- 유저 default 이미지 주소 설정
<br/>
<br/>
=> refactor: 유저 default 이미지 변경

src/models/users.model.ts
- User 테이블 img 컬럼 길이 변경(STRING(100) -> STRING(1000))
<br/>
<br/>
=> refactor: User 테이블 img 길이 변경

package-lock.json, package.json, src/app.ts, src/config/logs/error/.8f3512f5af0ac0bfd3db04cc68ce63805bfd550a-audit.json, src/config/logs/error/2024-08-12.error.log, src/config/logs/info/.855226107fa7d23d064a361ad3c616fb345dffc3-audit.json, src/config/logs/info/2024-08-12.info.log, src/config/morganMiddleware.ts, src/config/winston.ts, src/errorHandler/errorMiddleware.ts
- log library 적용 (winston, morgan)
<br/>
<br/>
=> feat: log library 적용

src/models/blacklists.model.ts, src/models/buying.model.ts, src/models/deliveryRegions.model.ts, src/models/orders.model.ts, src/models/regions.model.ts, src/models/reviews.model.ts, src/models/states.model.ts
=> feat: 공동구매 model 추가

src/app.ts, src/controllers/orders.controller.ts, src/dto/orders.dto.ts, src/models/orders.model.ts, src/routes/orders.route.ts, src/services/orders.service.ts, src/validators/orders.validator.ts
- 참여한 공동구매 내역 조회 API 추가
- 참여한 공동구매 summary 조회 API 추가
- orders 테이블에 created_at 추가
<br/>
공동구매 마감기한이 지나면 공동구매 달성 여부에 따라 자동으로 주문 상태를 변경하는 MySQL Event Scheduler를 설정했습니다.
=> feat: 참여한 공동구매 내역 조회

src/controllers/buyings.controller.ts, src/controllers/orders.controller.ts, src/models/orders.model.ts, src/routes/orders.route.ts, src/services/buyings.service.ts, src/services/orders.service.ts, src/validators/orders.validator.ts
- 주문 취소 API 추가
- 참여한 공동구매 상세 조회 API 추가
- 공동구매 신청 시 블랙리스트 확인 기능 추가
<br/>
<br/>
=> feat: 주문 취소 API 추가

jest.config.js, package-lock.json, package.json, src/app.ts, src/tests/liquors.test.ts
- jest 기본 설정
- 주류 카테고리 조회 테스트 추가
<br/>
테스트 파일은 src/tests 폴더 아래에 작성하면 됩니다.
<br/>
=> test: 주류 카테고리 조회 테스트 추가

src/controllers/buyings.controller.ts, src/controllers/orders.controller.ts, src/dto/buyings.dto.ts, src/dto/orders.dto.ts, src/models/buyings.model.ts, src/models/orders.model.ts, src/routes/orders.route.ts, src/services/buyings.service.ts, src/services/orders.service.ts
- 공동구매 참여 API에서 요청한 주문 수량이 최대 주문 가능 수량을 초과할 경우에 대한 예외 처리
- 참여한 공동구매 목록 조회 API 응답에 공동구매 번호, 총 가격, 주문 수량 추가
- 마감 기한 전에 주문을 취소하면 DB에서 삭제
<br/>
<br/>
=> refactor: 주문 관련 API 수정

package-lock.json, package.json, src/app.ts, src/controllers/buyings.controller.ts, src/controllers/regions.controller.ts, src/dto/buyings.dto.ts, src/routes/regions.route.ts, src/services/buyings.service.ts, src/services/orders.service.ts, src/services/regions.service.ts, src/utils/date.ts, src/validators/buyings.validator.ts
- 공동구매 참여 API 예외 처리 수정
- 요청한 주문 수량이 최대 주문 가능 수량을 초과할 경우
- 공동구매 진행 기간이 아닌 경우
- 공동구매 참여 API와 주문 취소 API의 timezone 관련 문제 수정
- 지역 목록 조회 API 추가
- 공동구매 목록 조회 API에 지역 필터링 기능 추가
<br/>
<br/>
=> refactor: 공동구매 목록 조회 지역 필터링 기능 추가

src/controllers/buyings.controller.ts, src/services/buyings.service.ts, src/services/orders.service.ts, src/utils/date.ts
- 현재 한국 시간을 반환하는 getTodayDate() 함수 수정
<br/>
<br/>
=> fix: timezone 문제 수정

src/app.ts
- 프론트 배포 주소 수정
- 프론트 admin 사이트 cors 설정 추가
<br/>
<br/>
=> refactor: 프론트 배포 주소 수정

package-lock.json, package.json, src/controllers/users.controller.ts, src/routes/users.route.ts, src/services/liquors.service.ts, src/services/users.service.ts, src/validators/users.validator.ts
- 네이버 OCR으로 입력받은 사업자등록증을 분석하여 사업자번호와 도매업체 여부를 반환하는 API 추가
- 도매업체가 회원가입 시 자동으로 도매업체 권한 부여
- 토큰 만료 시간을 .env 파일로 분리
- 도매업자 권한 신청 API 제거
<br/>
<br/>
=> feat: 사업자등록증 OCR API 추가

src/controllers/orders.controller.ts, src/dto/orders.dto.ts, src/routes/orders.route.ts, src/services/orders.service.ts, src/validators/orders.validator.ts
- 참여한 공동구매 목록 조회 API 페이지네이션 제거
- 참여한 공동구매 현황 조회 API 쿼리문 버그 수정
<br/>
<br/>
=> refactor: 참여한 공동구매 목록 조회 API 페이지네이션 제거

src/services/buyings.service.ts
- 공동구매 주문자 목록 조회 API (사업자 번호 -> 상호명)
<br/>
<br/>
=> refactor: 공동구매 주문자 목록 내용 수정

src/services/users.service.ts
=> fix: ocr 에러  로그 확인

src/services/users.service.ts
- ocr 응답 결과에서 인식 실패에 대한 예외 처리 추가
<br/>
이제 사업자등록증이 아닌 사진을 보내도 에러가 발생하지 않습니다.
<br/>
=> fix: ocr 결과 예외 처리 추가

src/services/sectors.service.ts
- 업종 카테고리 조회에서 도매업체 제외
<br/>
<br/>
=> refactor: 업종 조회에서 도매업체 제외
